// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: hlcv1.proto

package hlcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clock int64 `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hlcv1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_hlcv1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_hlcv1_proto_rawDescGZIP(), []int{0}
}

func (x *GetResp) GetClock() int64 {
	if x != nil {
		return x.Clock
	}
	return 0
}

type BatchGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// default count is 1, means that only get one.
	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// if count is more than two, return_first can be set to reduce the size of the response
	ReturnFirst bool `protobuf:"varint,2,opt,name=return_first,json=returnFirst,proto3" json:"return_first,omitempty"`
}

func (x *BatchGetReq) Reset() {
	*x = BatchGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hlcv1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetReq) ProtoMessage() {}

func (x *BatchGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_hlcv1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetReq.ProtoReflect.Descriptor instead.
func (*BatchGetReq) Descriptor() ([]byte, []int) {
	return file_hlcv1_proto_rawDescGZIP(), []int{1}
}

func (x *BatchGetReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BatchGetReq) GetReturnFirst() bool {
	if x != nil {
		return x.ReturnFirst
	}
	return false
}

type BatchGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *BatchGetReq `protobuf:"bytes,1,opt,name=Req,proto3" json:"Req,omitempty"`
	// if return_first specified true, first clock will be set
	First int64 `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	// if request count more than one and return_first = false, all clock allocated will be set here
	Clocks []int64 `protobuf:"varint,3,rep,packed,name=clocks,proto3" json:"clocks,omitempty"`
}

func (x *BatchGetResp) Reset() {
	*x = BatchGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hlcv1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResp) ProtoMessage() {}

func (x *BatchGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_hlcv1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResp.ProtoReflect.Descriptor instead.
func (*BatchGetResp) Descriptor() ([]byte, []int) {
	return file_hlcv1_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetResp) GetReq() *BatchGetReq {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *BatchGetResp) GetFirst() int64 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *BatchGetResp) GetClocks() []int64 {
	if x != nil {
		return x.Clocks
	}
	return nil
}

var File_hlcv1_proto protoreflect.FileDescriptor

var file_hlcv1_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x6c, 0x63, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68,
	0x6c, 0x63, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x63, 0x6b, 0x22, 0x46, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x0c, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6c, 0x63, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x52, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x32, 0x70,
	0x0a, 0x0a, 0x48, 0x43, 0x4c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x68, 0x6c,
	0x63, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x08, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x68, 0x6c, 0x63, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x68, 0x6c,
	0x63, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x68, 0x6c, 0x63, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_hlcv1_proto_rawDescOnce sync.Once
	file_hlcv1_proto_rawDescData = file_hlcv1_proto_rawDesc
)

func file_hlcv1_proto_rawDescGZIP() []byte {
	file_hlcv1_proto_rawDescOnce.Do(func() {
		file_hlcv1_proto_rawDescData = protoimpl.X.CompressGZIP(file_hlcv1_proto_rawDescData)
	})
	return file_hlcv1_proto_rawDescData
}

var file_hlcv1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hlcv1_proto_goTypes = []interface{}{
	(*GetResp)(nil),       // 0: hlcv1.GetResp
	(*BatchGetReq)(nil),   // 1: hlcv1.BatchGetReq
	(*BatchGetResp)(nil),  // 2: hlcv1.BatchGetResp
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_hlcv1_proto_depIdxs = []int32{
	1, // 0: hlcv1.BatchGetResp.Req:type_name -> hlcv1.BatchGetReq
	3, // 1: hlcv1.HCLService.Get:input_type -> google.protobuf.Empty
	1, // 2: hlcv1.HCLService.BatchGet:input_type -> hlcv1.BatchGetReq
	0, // 3: hlcv1.HCLService.Get:output_type -> hlcv1.GetResp
	2, // 4: hlcv1.HCLService.BatchGet:output_type -> hlcv1.BatchGetResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hlcv1_proto_init() }
func file_hlcv1_proto_init() {
	if File_hlcv1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hlcv1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hlcv1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hlcv1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hlcv1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hlcv1_proto_goTypes,
		DependencyIndexes: file_hlcv1_proto_depIdxs,
		MessageInfos:      file_hlcv1_proto_msgTypes,
	}.Build()
	File_hlcv1_proto = out.File
	file_hlcv1_proto_rawDesc = nil
	file_hlcv1_proto_goTypes = nil
	file_hlcv1_proto_depIdxs = nil
}
